service: resizer
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512

# you can overwrite defaults here
#  stage: prod
  stage: django
#  region: us-east-1
  environment:
#    BUCKET: cdn.tickle.life
#    URL: http://cdn.tickle.life.s3-website-us-east-1.amazonaws.com
    BUCKET: tlc-cdn
    URL: https://tlccdn.tickle.life

functions:
  resizer:
    handler: handler.resizer
    events:
      - http:
          path: resizer
          method: get
      - s3: ${env:BUCKET}

