service: resizer
provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1
  environment:
    BUCKET: cdn-dyn-2
    URL: http://cdn-dyn-2.s3-website-us-east-1.amazonaws.com

functions:
  resizer:
    handler: handler.resizer
    events:
      - http:
          path: resizer
          method: get
      - s3: ${env:BUCKET}