service: resizer
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512

# you can overwrite defaults here
#  stage: prod    # Used for tlccdn
#  stage: django  # Confused
  stage: wp       # Used for wp (cdn.tickle.life)
#  stage: ext       # Used for serving external images
#  region: us-east-1s
  environment:
    BUCKET: cdn.tickle.life
    URL: https://cdn.tickle.life
#    BUCKET: cdnext.tickle.life
#    URL: https://cdnext.tickle.life
#    BUCKET: tlc-cdn
#    URL: https://tlccdn.tickle.life

functions:
  resizer:
    handler: handler.resizer
    events:
      - http:
          path: resizer
          method: get
      - s3: ${env:BUCKET}
#  resizer:
#    handler: external.serve
#    events:
#      - http:
#          path: ext
#          method: get

